using System.Text.Json.Serialization;
using Bullish.Net.Objects.Internal;
using Bullish.Net.Objects.Models;

namespace Bullish.Net.Converters
{
    [JsonSerializable(typeof(BullishAsset[]))]
    [JsonSerializable(typeof(BullishAmmData))]
    [JsonSerializable(typeof(BullishAmmData[]))]
    [JsonSerializable(typeof(BullishAccountAsset))]
    [JsonSerializable(typeof(BullishAccountAsset[]))]
    [JsonSerializable(typeof(BullishAuthResponse))]
    [JsonSerializable(typeof(BullishBorrowInterest[]))]
    [JsonSerializable(typeof(BullishCollateralBand))]
    [JsonSerializable(typeof(BullishCollateralBand[]))]
    [JsonSerializable(typeof(BullishCryptoDepositInstruction[]))]
    [JsonSerializable(typeof(BullishCryptoWithdrawalInstruction[]))]
    [JsonSerializable(typeof(BullishCustodyTransaction[]))]
    [JsonSerializable(typeof(BullishDerivativePosition[]))]
    [JsonSerializable(typeof(BullishDerivativeSettlement[]))]
    [JsonSerializable(typeof(BullishFiatDepositInstruction[]))]
    [JsonSerializable(typeof(BullishFiatWithdrawalInstruction[]))]
    [JsonSerializable(typeof(BullishFeeTier))]
    [JsonSerializable(typeof(BullishFeeTier[]))]
    [JsonSerializable(typeof(BullishMmpConfigurationResult))]
    [JsonSerializable(typeof(BullishNonceRange))]
    [JsonSerializable(typeof(BullishOrder))]
    [JsonSerializable(typeof(BullishOrder[]))]
    [JsonSerializable(typeof(BullishPagedResult<BullishBorrowInterest>))]
    [JsonSerializable(typeof(BullishPagedResult<BullishCustodyTransaction>))]
    [JsonSerializable(typeof(BullishPagedResult<BullishDerivativeSettlement>))]
    [JsonSerializable(typeof(BullishPagedResult<BullishOrder>))]
    [JsonSerializable(typeof(BullishPagedResult<BullishTransfer>))]
    [JsonSerializable(typeof(BullishPagedResult<BullishUserTrade>))]
    [JsonSerializable(typeof(BullishPagedLinks))]
    [JsonSerializable(typeof(BullishSelfHostedWalletVerification[]))]
    [JsonSerializable(typeof(BullishSelfHostedWalletVerificationInstruction))]
    [JsonSerializable(typeof(BullishSymbol[]))]
    [JsonSerializable(typeof(BullishTimestamp))]
    [JsonSerializable(typeof(BullishTicker[]))]
    [JsonSerializable(typeof(BullishTradingAccount))]
    [JsonSerializable(typeof(BullishTradingAccount[]))]
    [JsonSerializable(typeof(BullishTransfer[]))]
    [JsonSerializable(typeof(BullishUnderlyingAsset))]
    [JsonSerializable(typeof(BullishUserTrade))]
    [JsonSerializable(typeof(BullishUserTrade[]))]
    [JsonSerializable(typeof(BullishWithdrawalLimit))]
    [JsonSerializable(typeof(BullishCreateOrderResult))]
    [JsonSerializable(typeof(BullishCancelOrderResult))]
    [JsonSerializable(typeof(BullishSocketResponse))]
    [JsonSerializable(typeof(BullishSocketRequest))]
    [JsonSerializable(typeof(BullishSubscriptionEvent<BullishTicker>))]
    [JsonSerializable(typeof(BullishSubscriptionEvent<BullishTradeSocketData>))]
    [JsonSerializable(typeof(BullishSubscriptionEvent<BullishOrderBook>))]
    [JsonSerializable(typeof(BullishSubscriptionEvent<BullishAccountAsset[]>))]
    [JsonSerializable(typeof(BullishSubscriptionEvent<BullishOrder[]>))]
    [JsonSerializable(typeof(BullishSubscriptionEvent<BullishUserTrade[]>))]
    internal partial class BullishSourceGenerationContext : JsonSerializerContext
    { }
}
